/* Generated and editorially frozen by scripts/build-content.mjs. */
import type { CountryRecord, LandmarkRecord } from './types.js';

export const COUNTRY_RECORDS = [
  {"id":"country-can","name":"Canada","iso2":"ca","iso3":"CAN","capital":"Ottawa","accepted":[],"area":9984670,"region":"Americas","subregion":"Northern America","difficulty":"foundation"},
  {"id":"country-usa","name":"United States","iso2":"us","iso3":"USA","capital":"Washington D.C.","accepted":["Washington"],"area":9833517,"region":"Americas","subregion":"Northern America","difficulty":"foundation"},
  {"id":"country-mex","name":"Mexico","iso2":"mx","iso3":"MEX","capital":"Mexico City","accepted":["Ciudad de Mexico"],"area":1964375,"region":"Americas","subregion":"Central America","difficulty":"foundation"},
  {"id":"country-bra","name":"Brazil","iso2":"br","iso3":"BRA","capital":"Brasília","accepted":[],"area":8515770,"region":"Americas","subregion":"South America","difficulty":"foundation"},
  {"id":"country-arg","name":"Argentina","iso2":"ar","iso3":"ARG","capital":"Buenos Aires","accepted":[],"area":2780400,"region":"Americas","subregion":"South America","difficulty":"foundation"},
  {"id":"country-chl","name":"Chile","iso2":"cl","iso3":"CHL","capital":"Santiago","accepted":["Santiago de Chile"],"area":756102,"region":"Americas","subregion":"South America","difficulty":"foundation"},
  {"id":"country-per","name":"Peru","iso2":"pe","iso3":"PER","capital":"Lima","accepted":[],"area":1285216,"region":"Americas","subregion":"South America","difficulty":"foundation"},
  {"id":"country-col","name":"Colombia","iso2":"co","iso3":"COL","capital":"Bogotá","accepted":[],"area":1138910,"region":"Americas","subregion":"South America","difficulty":"foundation"},
  {"id":"country-ecu","name":"Ecuador","iso2":"ec","iso3":"ECU","capital":"Quito","accepted":[],"area":283561,"region":"Americas","subregion":"South America","difficulty":"foundation"},
  {"id":"country-ury","name":"Uruguay","iso2":"uy","iso3":"URY","capital":"Montevideo","accepted":[],"area":176215,"region":"Americas","subregion":"South America","difficulty":"foundation"},
  {"id":"country-gbr","name":"United Kingdom","iso2":"gb","iso3":"GBR","capital":"London","accepted":[],"area":243610,"region":"Europe","subregion":"Northern Europe","difficulty":"foundation"},
  {"id":"country-fra","name":"France","iso2":"fr","iso3":"FRA","capital":"Paris","accepted":[],"area":643801,"region":"Europe","subregion":"Western Europe","difficulty":"foundation"},
  {"id":"country-deu","name":"Germany","iso2":"de","iso3":"DEU","capital":"Berlin","accepted":[],"area":357022,"region":"Europe","subregion":"Western Europe","difficulty":"foundation"},
  {"id":"country-esp","name":"Spain","iso2":"es","iso3":"ESP","capital":"Madrid","accepted":[],"area":505370,"region":"Europe","subregion":"Southern Europe","difficulty":"foundation"},
  {"id":"country-ita","name":"Italy","iso2":"it","iso3":"ITA","capital":"Rome","accepted":[],"area":301340,"region":"Europe","subregion":"Southern Europe","difficulty":"foundation"},
  {"id":"country-prt","name":"Portugal","iso2":"pt","iso3":"PRT","capital":"Lisbon","accepted":[],"area":92090,"region":"Europe","subregion":"Southern Europe","difficulty":"foundation"},
  {"id":"country-nld","name":"Netherlands","iso2":"nl","iso3":"NLD","capital":"Amsterdam","accepted":[],"area":41543,"region":"Europe","subregion":"Western Europe","difficulty":"foundation"},
  {"id":"country-bel","name":"Belgium","iso2":"be","iso3":"BEL","capital":"Brussels","accepted":[],"area":30528,"region":"Europe","subregion":"Western Europe","difficulty":"foundation"},
  {"id":"country-che","name":"Switzerland","iso2":"ch","iso3":"CHE","capital":"Bern","accepted":[],"area":41277,"region":"Europe","subregion":"Western Europe","difficulty":"foundation"},
  {"id":"country-aut","name":"Austria","iso2":"at","iso3":"AUT","capital":"Vienna","accepted":[],"area":83871,"region":"Europe","subregion":"Western Europe","difficulty":"foundation"},
  {"id":"country-pol","name":"Poland","iso2":"pl","iso3":"POL","capital":"Warsaw","accepted":["Warszawa"],"area":312685,"region":"Europe","subregion":"Eastern Europe","difficulty":"foundation"},
  {"id":"country-grc","name":"Greece","iso2":"gr","iso3":"GRC","capital":"Athens","accepted":[],"area":131957,"region":"Europe","subregion":"Southern Europe","difficulty":"foundation"},
  {"id":"country-irl","name":"Ireland","iso2":"ie","iso3":"IRL","capital":"Dublin","accepted":[],"area":70273,"region":"Europe","subregion":"Northern Europe","difficulty":"foundation"},
  {"id":"country-nor","name":"Norway","iso2":"no","iso3":"NOR","capital":"Oslo","accepted":[],"area":323802,"region":"Europe","subregion":"Northern Europe","difficulty":"foundation"},
  {"id":"country-swe","name":"Sweden","iso2":"se","iso3":"SWE","capital":"Stockholm","accepted":[],"area":450295,"region":"Europe","subregion":"Northern Europe","difficulty":"foundation"},
  {"id":"country-fin","name":"Finland","iso2":"fi","iso3":"FIN","capital":"Helsinki","accepted":[],"area":338145,"region":"Europe","subregion":"Northern Europe","difficulty":"foundation"},
  {"id":"country-dnk","name":"Denmark","iso2":"dk","iso3":"DNK","capital":"Copenhagen","accepted":[],"area":43094,"region":"Europe","subregion":"Northern Europe","difficulty":"foundation"},
  {"id":"country-isl","name":"Iceland","iso2":"is","iso3":"ISL","capital":"Reykjavik","accepted":[],"area":103000,"region":"Europe","subregion":"Northern Europe","difficulty":"foundation"},
  {"id":"country-cze","name":"Czechia","iso2":"cz","iso3":"CZE","capital":"Prague","accepted":[],"area":78867,"region":"Europe","subregion":"Eastern Europe","difficulty":"foundation"},
  {"id":"country-hun","name":"Hungary","iso2":"hu","iso3":"HUN","capital":"Budapest","accepted":[],"area":93028,"region":"Europe","subregion":"Eastern Europe","difficulty":"foundation"},
  {"id":"country-rus","name":"Russia","iso2":"ru","iso3":"RUS","capital":"Moscow","accepted":[],"area":17098242,"region":"Europe","subregion":"Eastern Europe","difficulty":"foundation"},
  {"id":"country-ukr","name":"Ukraine","iso2":"ua","iso3":"UKR","capital":"Kyiv","accepted":[],"area":603550,"region":"Europe","subregion":"Eastern Europe","difficulty":"foundation"},
  {"id":"country-tur","name":"Türkiye","iso2":"tr","iso3":"TUR","capital":"Ankara","accepted":[],"area":783562,"region":"Asia","subregion":"Western Asia","difficulty":"foundation"},
  {"id":"country-egy","name":"Egypt","iso2":"eg","iso3":"EGY","capital":"Cairo","accepted":[],"area":1001450,"region":"Africa","subregion":"Northern Africa","difficulty":"foundation"},
  {"id":"country-nga","name":"Nigeria","iso2":"ng","iso3":"NGA","capital":"Abuja","accepted":[],"area":923768,"region":"Africa","subregion":"Western Africa","difficulty":"foundation"},
  {"id":"country-ken","name":"Kenya","iso2":"ke","iso3":"KEN","capital":"Nairobi","accepted":[],"area":580367,"region":"Africa","subregion":"Eastern Africa","difficulty":"foundation"},
  {"id":"country-eth","name":"Ethiopia","iso2":"et","iso3":"ETH","capital":"Addis Ababa","accepted":[],"area":1104300,"region":"Africa","subregion":"Eastern Africa","difficulty":"foundation"},
  {"id":"country-mar","name":"Morocco","iso2":"ma","iso3":"MAR","capital":"Rabat","accepted":[],"area":716550,"region":"Africa","subregion":"Northern Africa","difficulty":"foundation"},
  {"id":"country-gha","name":"Ghana","iso2":"gh","iso3":"GHA","capital":"Accra","accepted":[],"area":238533,"region":"Africa","subregion":"Western Africa","difficulty":"foundation"},
  {"id":"country-dza","name":"Algeria","iso2":"dz","iso3":"DZA","capital":"Algiers","accepted":[],"area":2381740,"region":"Africa","subregion":"Northern Africa","difficulty":"foundation"},
  {"id":"country-chn","name":"China","iso2":"cn","iso3":"CHN","capital":"Beijing","accepted":[],"area":9596960,"region":"Asia","subregion":"Eastern Asia","difficulty":"foundation"},
  {"id":"country-jpn","name":"Japan","iso2":"jp","iso3":"JPN","capital":"Tokyo","accepted":[],"area":377915,"region":"Asia","subregion":"Eastern Asia","difficulty":"foundation"},
  {"id":"country-ind","name":"India","iso2":"in","iso3":"IND","capital":"New Delhi","accepted":[],"area":3287263,"region":"Asia","subregion":"Southern Asia","difficulty":"foundation"},
  {"id":"country-idn","name":"Indonesia","iso2":"id","iso3":"IDN","capital":"Jakarta","accepted":[],"area":1904569,"region":"Asia","subregion":"South-Eastern Asia","difficulty":"foundation"},
  {"id":"country-kor","name":"South Korea","iso2":"kr","iso3":"KOR","capital":"Seoul","accepted":[],"area":99720,"region":"Asia","subregion":"Eastern Asia","difficulty":"foundation"},
  {"id":"country-tha","name":"Thailand","iso2":"th","iso3":"THA","capital":"Bangkok","accepted":[],"area":513120,"region":"Asia","subregion":"South-Eastern Asia","difficulty":"foundation"},
  {"id":"country-vnm","name":"Vietnam","iso2":"vn","iso3":"VNM","capital":"Hanoi","accepted":[],"area":331210,"region":"Asia","subregion":"South-Eastern Asia","difficulty":"foundation"},
  {"id":"country-phl","name":"Philippines","iso2":"ph","iso3":"PHL","capital":"Manila","accepted":[],"area":300000,"region":"Asia","subregion":"South-Eastern Asia","difficulty":"foundation"},
  {"id":"country-aus","name":"Australia","iso2":"au","iso3":"AUS","capital":"Canberra","accepted":[],"area":7741220,"region":"Oceania","subregion":"Australia and New Zealand","difficulty":"foundation"},
  {"id":"country-nzl","name":"New Zealand","iso2":"nz","iso3":"NZL","capital":"Wellington","accepted":[],"area":268838,"region":"Oceania","subregion":"Australia and New Zealand","difficulty":"foundation"},
  {"id":"country-pry","name":"Paraguay","iso2":"py","iso3":"PRY","capital":"Asunción","accepted":[],"area":406752,"region":"Americas","subregion":"South America","difficulty":"explorer"},
  {"id":"country-cri","name":"Costa Rica","iso2":"cr","iso3":"CRI","capital":"San José","accepted":[],"area":51100,"region":"Americas","subregion":"Central America","difficulty":"explorer"},
  {"id":"country-cub","name":"Cuba","iso2":"cu","iso3":"CUB","capital":"Havana","accepted":[],"area":110860,"region":"Americas","subregion":"Caribbean","difficulty":"explorer"},
  {"id":"country-dom","name":"Dominican Republic","iso2":"do","iso3":"DOM","capital":"Santo Domingo","accepted":[],"area":48670,"region":"Americas","subregion":"Caribbean","difficulty":"explorer"},
  {"id":"country-gtm","name":"Guatemala","iso2":"gt","iso3":"GTM","capital":"Guatemala City","accepted":[],"area":108889,"region":"Americas","subregion":"Central America","difficulty":"explorer"},
  {"id":"country-pan","name":"Panama","iso2":"pa","iso3":"PAN","capital":"Panama City","accepted":[],"area":75420,"region":"Americas","subregion":"Central America","difficulty":"explorer"},
  {"id":"country-jam","name":"Jamaica","iso2":"jm","iso3":"JAM","capital":"Kingston","accepted":[],"area":10991,"region":"Americas","subregion":"Caribbean","difficulty":"explorer"},
  {"id":"country-guy","name":"Guyana","iso2":"gy","iso3":"GUY","capital":"Georgetown","accepted":[],"area":214969,"region":"Americas","subregion":"South America","difficulty":"explorer"},
  {"id":"country-rou","name":"Romania","iso2":"ro","iso3":"ROU","capital":"Bucharest","accepted":[],"area":238391,"region":"Europe","subregion":"Eastern Europe","difficulty":"explorer"},
  {"id":"country-bgr","name":"Bulgaria","iso2":"bg","iso3":"BGR","capital":"Sofia","accepted":[],"area":110879,"region":"Europe","subregion":"Eastern Europe","difficulty":"explorer"},
  {"id":"country-hrv","name":"Croatia","iso2":"hr","iso3":"HRV","capital":"Zagreb","accepted":[],"area":56594,"region":"Europe","subregion":"Southern Europe","difficulty":"explorer"},
  {"id":"country-srb","name":"Serbia","iso2":"rs","iso3":"SRB","capital":"Belgrade","accepted":[],"area":77474,"region":"Europe","subregion":"Southern Europe","difficulty":"explorer"},
  {"id":"country-svk","name":"Slovakia","iso2":"sk","iso3":"SVK","capital":"Bratislava","accepted":[],"area":49035,"region":"Europe","subregion":"Eastern Europe","difficulty":"explorer"},
  {"id":"country-svn","name":"Slovenia","iso2":"si","iso3":"SVN","capital":"Ljubljana","accepted":[],"area":20273,"region":"Europe","subregion":"Southern Europe","difficulty":"explorer"},
  {"id":"country-est","name":"Estonia","iso2":"ee","iso3":"EST","capital":"Tallinn","accepted":[],"area":45228,"region":"Europe","subregion":"Northern Europe","difficulty":"explorer"},
  {"id":"country-lva","name":"Latvia","iso2":"lv","iso3":"LVA","capital":"Riga","accepted":[],"area":64589,"region":"Europe","subregion":"Northern Europe","difficulty":"explorer"},
  {"id":"country-ltu","name":"Lithuania","iso2":"lt","iso3":"LTU","capital":"Vilnius","accepted":[],"area":65300,"region":"Europe","subregion":"Northern Europe","difficulty":"explorer"},
  {"id":"country-blr","name":"Belarus","iso2":"by","iso3":"BLR","capital":"Minsk","accepted":[],"area":207600,"region":"Europe","subregion":"Eastern Europe","difficulty":"explorer"},
  {"id":"country-kaz","name":"Kazakhstan","iso2":"kz","iso3":"KAZ","capital":"Astana","accepted":[],"area":2724900,"region":"Asia","subregion":"Central Asia","difficulty":"explorer"},
  {"id":"country-mng","name":"Mongolia","iso2":"mn","iso3":"MNG","capital":"Ulaanbaatar","accepted":["Ulan Bator"],"area":1564116,"region":"Asia","subregion":"Eastern Asia","difficulty":"explorer"},
  {"id":"country-uzb","name":"Uzbekistan","iso2":"uz","iso3":"UZB","capital":"Tashkent","accepted":[],"area":447400,"region":"Asia","subregion":"Central Asia","difficulty":"explorer"},
  {"id":"country-sau","name":"Saudi Arabia","iso2":"sa","iso3":"SAU","capital":"Riyadh","accepted":[],"area":2149690,"region":"Asia","subregion":"Western Asia","difficulty":"explorer"},
  {"id":"country-are","name":"United Arab Emirates","iso2":"ae","iso3":"ARE","capital":"Abu Dhabi","accepted":[],"area":83600,"region":"Asia","subregion":"Western Asia","difficulty":"explorer"},
  {"id":"country-jor","name":"Jordan","iso2":"jo","iso3":"JOR","capital":"Amman","accepted":[],"area":89342,"region":"Asia","subregion":"Western Asia","difficulty":"explorer"},
  {"id":"country-irn","name":"Iran","iso2":"ir","iso3":"IRN","capital":"Tehran","accepted":[],"area":1648195,"region":"Asia","subregion":"Southern Asia","difficulty":"explorer"},
  {"id":"country-irq","name":"Iraq","iso2":"iq","iso3":"IRQ","capital":"Baghdad","accepted":[],"area":438317,"region":"Asia","subregion":"Western Asia","difficulty":"explorer"},
  {"id":"country-pak","name":"Pakistan","iso2":"pk","iso3":"PAK","capital":"Islamabad","accepted":[],"area":796095,"region":"Asia","subregion":"Southern Asia","difficulty":"explorer"},
  {"id":"country-bgd","name":"Bangladesh","iso2":"bd","iso3":"BGD","capital":"Dhaka","accepted":[],"area":148460,"region":"Asia","subregion":"Southern Asia","difficulty":"explorer"},
  {"id":"country-npl","name":"Nepal","iso2":"np","iso3":"NPL","capital":"Kathmandu","accepted":[],"area":147181,"region":"Asia","subregion":"Southern Asia","difficulty":"explorer"},
  {"id":"country-mys","name":"Malaysia","iso2":"my","iso3":"MYS","capital":"Kuala Lumpur","accepted":[],"area":329847,"region":"Asia","subregion":"South-Eastern Asia","difficulty":"explorer"},
  {"id":"country-sgp","name":"Singapore","iso2":"sg","iso3":"SGP","capital":"Singapore","accepted":[],"area":719,"region":"Asia","subregion":"South-Eastern Asia","difficulty":"explorer"},
  {"id":"country-khm","name":"Cambodia","iso2":"kh","iso3":"KHM","capital":"Phnom Penh","accepted":[],"area":181035,"region":"Asia","subregion":"South-Eastern Asia","difficulty":"explorer"},
  {"id":"country-lao","name":"Laos","iso2":"la","iso3":"LAO","capital":"Vientiane","accepted":[],"area":236800,"region":"Asia","subregion":"South-Eastern Asia","difficulty":"explorer"},
  {"id":"country-tun","name":"Tunisia","iso2":"tn","iso3":"TUN","capital":"Tunis","accepted":[],"area":163610,"region":"Africa","subregion":"Northern Africa","difficulty":"explorer"},
  {"id":"country-sen","name":"Senegal","iso2":"sn","iso3":"SEN","capital":"Dakar","accepted":[],"area":196722,"region":"Africa","subregion":"Western Africa","difficulty":"explorer"},
  {"id":"country-bhr","name":"Bahrain","iso2":"bh","iso3":"BHR","capital":"Manama","accepted":[],"area":760,"region":"Asia","subregion":"Western Asia","difficulty":"expert"},
  {"id":"country-omn","name":"Oman","iso2":"om","iso3":"OMN","capital":"Muscat","accepted":[],"area":309500,"region":"Asia","subregion":"Western Asia","difficulty":"expert"},
  {"id":"country-qat","name":"Qatar","iso2":"qa","iso3":"QAT","capital":"Doha","accepted":[],"area":11586,"region":"Asia","subregion":"Western Asia","difficulty":"expert"},
  {"id":"country-kwt","name":"Kuwait","iso2":"kw","iso3":"KWT","capital":"Kuwait City","accepted":[],"area":17818,"region":"Asia","subregion":"Western Asia","difficulty":"expert"},
  {"id":"country-kgz","name":"Kyrgyzstan","iso2":"kg","iso3":"KGZ","capital":"Bishkek","accepted":[],"area":199951,"region":"Asia","subregion":"Central Asia","difficulty":"expert"},
  {"id":"country-tjk","name":"Tajikistan","iso2":"tj","iso3":"TJK","capital":"Dushanbe","accepted":[],"area":144100,"region":"Asia","subregion":"Central Asia","difficulty":"expert"},
  {"id":"country-tkm","name":"Turkmenistan","iso2":"tm","iso3":"TKM","capital":"Ashgabat","accepted":[],"area":488100,"region":"Asia","subregion":"Central Asia","difficulty":"expert"},
  {"id":"country-brn","name":"Brunei","iso2":"bn","iso3":"BRN","capital":"Bandar Seri Begawan","accepted":[],"area":5765,"region":"Asia","subregion":"South-Eastern Asia","difficulty":"expert"},
  {"id":"country-btn","name":"Bhutan","iso2":"bt","iso3":"BTN","capital":"Thimphu","accepted":[],"area":38394,"region":"Asia","subregion":"Southern Asia","difficulty":"expert"},
  {"id":"country-mdv","name":"Maldives","iso2":"mv","iso3":"MDV","capital":"Malé","accepted":[],"area":298,"region":"Asia","subregion":"Southern Asia","difficulty":"expert"},
  {"id":"country-bwa","name":"Botswana","iso2":"bw","iso3":"BWA","capital":"Gaborone","accepted":[],"area":581730,"region":"Africa","subregion":"Southern Africa","difficulty":"expert"},
  {"id":"country-nam","name":"Namibia","iso2":"na","iso3":"NAM","capital":"Windhoek","accepted":[],"area":824292,"region":"Africa","subregion":"Southern Africa","difficulty":"expert"},
  {"id":"country-moz","name":"Mozambique","iso2":"mz","iso3":"MOZ","capital":"Maputo","accepted":[],"area":799380,"region":"Africa","subregion":"Eastern Africa","difficulty":"expert"},
  {"id":"country-mdg","name":"Madagascar","iso2":"mg","iso3":"MDG","capital":"Antananarivo","accepted":[],"area":587041,"region":"Africa","subregion":"Eastern Africa","difficulty":"expert"},
  {"id":"country-mus","name":"Mauritius","iso2":"mu","iso3":"MUS","capital":"Port Louis","accepted":[],"area":2040,"region":"Africa","subregion":"Eastern Africa","difficulty":"expert"},
] as const satisfies readonly CountryRecord[];

export const LANDMARK_RECORDS = [
  {"id":"landmark-001","name":"Memphis and its Necropolis – the Pyramid Fields from Giza to Dahshur","country":"Egypt","difficulty":"foundation"},
  {"id":"landmark-002","name":"Ancient Thebes with its Necropolis","country":"Egypt","difficulty":"foundation"},
  {"id":"landmark-003","name":"Petra","country":"Jordan","difficulty":"foundation"},
  {"id":"landmark-004","name":"Angkor","country":"Cambodia","difficulty":"foundation"},
  {"id":"landmark-005","name":"The Great Wall","country":"China","difficulty":"foundation"},
  {"id":"landmark-006","name":"Taj Mahal","country":"India","difficulty":"foundation"},
  {"id":"landmark-007","name":"Historic Sanctuary of Machu Picchu","country":"Peru","difficulty":"foundation"},
  {"id":"landmark-008","name":"Acropolis, Athens","country":"Greece","difficulty":"foundation"},
  {"id":"landmark-009","name":"Archaeological Areas of Pompei, Herculaneum and Torre Annunziata","country":"Italy","difficulty":"foundation"},
  {"id":"landmark-010","name":"Historic Centre of Rome","country":"Italy","difficulty":"foundation"},
  {"id":"landmark-011","name":"Mont-Saint-Michel and its Bay","country":"France","difficulty":"foundation"},
  {"id":"landmark-012","name":"Palace and Park of Versailles","country":"France","difficulty":"foundation"},
  {"id":"landmark-013","name":"Stonehenge, Avebury and Associated Sites","country":"United Kingdom","difficulty":"foundation"},
  {"id":"landmark-014","name":"Tower of London","country":"United Kingdom","difficulty":"foundation"},
  {"id":"landmark-015","name":"Cologne Cathedral","country":"Germany","difficulty":"foundation"},
  {"id":"landmark-016","name":"Museumsinsel (Museum Island), Berlin","country":"Germany","difficulty":"foundation"},
  {"id":"landmark-017","name":"Alhambra, Generalife and Albayzín, Granada","country":"Spain","difficulty":"foundation"},
  {"id":"landmark-018","name":"Works of Antoni Gaudí","country":"Spain","difficulty":"foundation"},
  {"id":"landmark-019","name":"Monastery of the Hieronymites and Tower of Belém","country":"Portugal","difficulty":"foundation"},
  {"id":"landmark-020","name":"Historic Centre of Prague","country":"Czechia","difficulty":"foundation"},
  {"id":"landmark-021","name":"Budapest, including the Banks of the Danube","country":"Hungary","difficulty":"foundation"},
  {"id":"landmark-022","name":"Historic Centre of Vienna","country":"Austria","difficulty":"foundation"},
  {"id":"landmark-023","name":"Old City of Dubrovnik","country":"Croatia","difficulty":"foundation"},
  {"id":"landmark-024","name":"Historic Centre of Kraków","country":"Poland","difficulty":"foundation"},
  {"id":"landmark-025","name":"Auschwitz Birkenau","country":"Poland","difficulty":"foundation"},
  {"id":"landmark-026","name":"Rila Monastery","country":"Bulgaria","difficulty":"foundation"},
  {"id":"landmark-027","name":"Bryggen","country":"Norway","difficulty":"foundation"},
  {"id":"landmark-028","name":"Historic Centre (Old Town) of Tallinn","country":"Estonia","difficulty":"foundation"},
  {"id":"landmark-029","name":"Historic Centre of Riga","country":"Latvia","difficulty":"foundation"},
  {"id":"landmark-030","name":"Vilnius Historic Centre","country":"Lithuania","difficulty":"foundation"},
  {"id":"landmark-031","name":"Fortress of Suomenlinna","country":"Finland","difficulty":"foundation"},
  {"id":"landmark-032","name":"Royal Domain of Drottningholm","country":"Sweden","difficulty":"foundation"},
  {"id":"landmark-033","name":"Þingvellir National Park","country":"Iceland","difficulty":"foundation"},
  {"id":"landmark-034","name":"La Grand-Place, Brussels","country":"Belgium","difficulty":"foundation"},
  {"id":"landmark-035","name":"Mill Network at Kinderdijk-Elshout","country":"Netherlands","difficulty":"foundation"},
  {"id":"landmark-036","name":"City of Luxembourg: its Old Quarters and Fortifications","country":"Luxembourg","difficulty":"foundation"},
  {"id":"landmark-037","name":"Swiss Alps Jungfrau-Aletsch","country":"Switzerland","difficulty":"foundation"},
  {"id":"landmark-038","name":"Vatican City","country":"Vatican City","difficulty":"foundation"},
  {"id":"landmark-039","name":"Monasteries of Meteora","country":"Greece","difficulty":"foundation"},
  {"id":"landmark-040","name":"Monastery of Geghard and the Upper Azat Valley","country":"Armenia","difficulty":"foundation"},
  {"id":"landmark-041","name":"Historic Areas of Istanbul","country":"Türkiye","difficulty":"foundation"},
  {"id":"landmark-042","name":"Göreme National Park and the Rock Sites of Cappadocia","country":"Türkiye","difficulty":"foundation"},
  {"id":"landmark-043","name":"Persepolis","country":"Iran","difficulty":"foundation"},
  {"id":"landmark-044","name":"Babylon","country":"Iraq","difficulty":"foundation"},
  {"id":"landmark-045","name":"Baalbek","country":"Lebanon","difficulty":"foundation"},
  {"id":"landmark-046","name":"Masada","country":"Israel","difficulty":"foundation"},
  {"id":"landmark-047","name":"Hegra Archaeological Site","country":"Saudi Arabia","difficulty":"foundation"},
  {"id":"landmark-048","name":"Al Zubarah Archaeological Site","country":"Qatar","difficulty":"foundation"},
  {"id":"landmark-049","name":"Cultural Sites of Al Ain","country":"United Arab Emirates","difficulty":"foundation"},
  {"id":"landmark-050","name":"Land of Frankincense","country":"Oman","difficulty":"foundation"},
  {"id":"landmark-051","name":"Samarkand – Crossroad of Cultures","country":"Uzbekistan","difficulty":"explorer"},
  {"id":"landmark-052","name":"Mausoleum of Khoja Ahmed Yasawi","country":"Kazakhstan","difficulty":"explorer"},
  {"id":"landmark-053","name":"Kathmandu Valley","country":"Nepal","difficulty":"explorer"},
  {"id":"landmark-054","name":"Ruins of the Buddhist Vihara at Paharpur","country":"Bangladesh","difficulty":"explorer"},
  {"id":"landmark-055","name":"Ancient City of Sigiriya","country":"Sri Lanka","difficulty":"explorer"},
  {"id":"landmark-056","name":"Bagan","country":"Myanmar","difficulty":"explorer"},
  {"id":"landmark-057","name":"Town of Luang Prabang","country":"Laos","difficulty":"explorer"},
  {"id":"landmark-058","name":"Historic City of Ayutthaya","country":"Thailand","difficulty":"explorer"},
  {"id":"landmark-059","name":"Ha Long Bay - Cat Ba Archipelago","country":"Vietnam","difficulty":"explorer"},
  {"id":"landmark-060","name":"Hoi An Ancient Town","country":"Vietnam","difficulty":"explorer"},
  {"id":"landmark-061","name":"Melaka and George Town, Historic Cities of the Straits of Malacca","country":"Malaysia","difficulty":"explorer"},
  {"id":"landmark-062","name":"Singapore Botanic Gardens","country":"Singapore","difficulty":"explorer"},
  {"id":"landmark-063","name":"Borobudur Temple Compounds","country":"Indonesia","difficulty":"explorer"},
  {"id":"landmark-064","name":"Rice Terraces of the Philippine Cordilleras","country":"Philippines","difficulty":"explorer"},
  {"id":"landmark-065","name":"Historic Monuments of Ancient Kyoto","country":"Japan","difficulty":"explorer"},
  {"id":"landmark-066","name":"Itsukushima Shinto Shrine","country":"Japan","difficulty":"explorer"},
  {"id":"landmark-067","name":"Changdeokgung Palace Complex","country":"South Korea","difficulty":"explorer"},
  {"id":"landmark-068","name":"Orkhon Valley Cultural Landscape","country":"Mongolia","difficulty":"explorer"},
  {"id":"landmark-069","name":"Sydney Opera House","country":"Australia","difficulty":"explorer"},
  {"id":"landmark-070","name":"Te Wāhipounamu – South West New Zealand","country":"New Zealand","difficulty":"explorer"},
  {"id":"landmark-071","name":"Chief Roi Mata's Domain","country":"Vanuatu","difficulty":"explorer"},
  {"id":"landmark-072","name":"Kuk Early Agricultural Site","country":"Papua New Guinea","difficulty":"explorer"},
  {"id":"landmark-073","name":"Rapa Nui National Park","country":"Chile","difficulty":"explorer"},
  {"id":"landmark-074","name":"City of Quito","country":"Ecuador","difficulty":"explorer"},
  {"id":"landmark-075","name":"Port, Fortresses and Group of Monuments, Cartagena","country":"Colombia","difficulty":"explorer"},
  {"id":"landmark-076","name":"Historic Centre of Salvador de Bahia","country":"Brazil","difficulty":"explorer"},
  {"id":"landmark-077","name":"Brasilia","country":"Brazil","difficulty":"explorer"},
  {"id":"landmark-078","name":"Los Glaciares National Park","country":"Argentina","difficulty":"explorer"},
  {"id":"landmark-079","name":"Tiwanaku: Spiritual and Political Centre of the Tiwanaku Culture","country":"Bolivia","difficulty":"explorer"},
  {"id":"landmark-080","name":"Pre-Hispanic City of Chichen-Itza","country":"Mexico","difficulty":"explorer"},
  {"id":"landmark-081","name":"Pre-Hispanic City of Teotihuacan","country":"Mexico","difficulty":"explorer"},
  {"id":"landmark-082","name":"Tikal National Park","country":"Guatemala","difficulty":"explorer"},
  {"id":"landmark-083","name":"Maya Site of Copan","country":"Honduras","difficulty":"explorer"},
  {"id":"landmark-084","name":"Joya de Cerén Archaeological Site","country":"El Salvador","difficulty":"explorer"},
  {"id":"landmark-085","name":"Old Havana and its Fortification System","country":"Cuba","difficulty":"explorer"},
  {"id":"landmark-086","name":"Colonial City of Santo Domingo","country":"Dominican Republic","difficulty":"expert"},
  {"id":"landmark-087","name":"Canadian Rocky Mountain Parks","country":"Canada","difficulty":"expert"},
  {"id":"landmark-088","name":"Statue of Liberty","country":"United States","difficulty":"expert"},
  {"id":"landmark-089","name":"Yellowstone National Park","country":"United States","difficulty":"expert"},
  {"id":"landmark-090","name":"Rock-Hewn Churches, Lalibela","country":"Ethiopia","difficulty":"expert"},
  {"id":"landmark-091","name":"Serengeti National Park","country":"Tanzania","difficulty":"expert"},
  {"id":"landmark-092","name":"Great Zimbabwe National Monument","country":"Zimbabwe","difficulty":"expert"},
  {"id":"landmark-093","name":"Robben Island","country":"South Africa","difficulty":"expert"},
  {"id":"landmark-094","name":"Island of Mozambique","country":"Mozambique","difficulty":"expert"},
  {"id":"landmark-095","name":"Stone Town of Zanzibar","country":"Tanzania","difficulty":"expert"},
  {"id":"landmark-096","name":"Bwindi Impenetrable National Park","country":"Uganda","difficulty":"expert"},
  {"id":"landmark-097","name":"Forts and Castles, Volta, Greater Accra, Central and Western Regions","country":"Ghana","difficulty":"expert"},
  {"id":"landmark-098","name":"Island of Gorée","country":"Senegal","difficulty":"expert"},
  {"id":"landmark-099","name":"Timbuktu","country":"Mali","difficulty":"expert"},
  {"id":"landmark-100","name":"Lamu Old Town","country":"Kenya","difficulty":"expert"},
] as const satisfies readonly LandmarkRecord[];
