import type { ModeId } from '../engine/types.js';
import type { HlPack, HlPackQuestion } from '../modes/higherLower.js';
import type { McPack } from '../modes/multipleChoice.js';
import type { TaPack } from '../modes/typeAnswer.js';
import type { TfPack } from '../modes/trueFalse.js';
import type { Category, CountryFact } from './types.js';

/** Any unchanged rules-module pack generated by the product dataset. */
export type ProductPack = McPack | TfPack | TaPack | HlPack;

function explanation(fact: CountryFact): string {
  return `${fact.capital} is the capital of ${questionName(fact)}.`;
}

function questionName(fact: CountryFact): string {
  return fact.name === 'United States' ? 'the United States' : fact.name;
}

function multipleChoice(category: Category): McPack {
  const facts = category.facts;
  return {
    packId: `${category.id}-capitals-mc-v1`,
    questions: facts.map((fact, index) => ({
      prompt: `${fact.flag} · What is the capital of ${questionName(fact)}?`,
      correct: fact.capital,
      wrong: [1, 2, 3].map((step) => facts[(index + step) % facts.length]!.capital) as [string, string, string],
      explanation: explanation(fact),
    })),
  };
}

function trueFalse(category: Category): TfPack {
  const facts = category.facts;
  return {
    packId: `${category.id}-capitals-tf-v1`,
    labels: ['True', 'False'],
    // Exactly one statement per country prevents a round from asking the same
    // underlying fact twice in true and false forms.
    questions: facts.map((fact, index) => {
      const isTrue = index % 2 === 0;
      const shown = isTrue ? fact.capital : facts[(index + 7) % facts.length]!.capital;
      return {
        statement: `${fact.flag} · ${shown} is the capital of ${questionName(fact)}.`,
        isTrue,
        explanation: explanation(fact),
      };
    }),
  };
}

function typeAnswer(category: Category): TaPack {
  return {
    packId: `${category.id}-capitals-type-v1`,
    questions: category.facts.map((fact) => ({
      prompt: `${fact.flag} · Type the capital of ${questionName(fact)}.`,
      acceptedAnswers: [fact.capital, ...(fact.accepted ?? [])],
      explanation: explanation(fact),
    })),
  };
}

function pairs(facts: CountryFact[]): HlPackQuestion[] {
  const result: HlPackQuestion[] = [];
  for (let a = 0; a < facts.length; a += 1) {
    for (let b = a + 1; b < facts.length; b += 1) {
      const first = facts[a]!;
      const second = facts[b]!;
      result.push({
        a: { label: `${first.flag} · ${first.name}`, value: first.area },
        b: { label: `${second.flag} · ${second.name}`, value: second.area },
      });
    }
  }
  return result;
}

function higherLower(category: Category): HlPack {
  return {
    packId: `${category.id}-area-hl-v1`,
    prompt: 'Which country has the larger total area?',
    unit: 'km²',
    explanation: 'Compared by total area, including inland water.',
    questions: pairs(category.facts),
  };
}

/** Build the selected region's pack without changing any rules module. */
export function getPack(category: Category, modeId: ModeId): ProductPack {
  if (modeId === 'multiple-choice') return multipleChoice(category);
  if (modeId === 'true-false') return trueFalse(category);
  if (modeId === 'type-answer') return typeAnswer(category);
  return higherLower(category);
}
