import type { ModeId, PresentedVisual } from '../engine/types.js';
import type { HlPack, HlPackQuestion } from '../modes/higherLower.js';
import type { McPack } from '../modes/multipleChoice.js';
import type { TaPack } from '../modes/typeAnswer.js';
import type { TfPack } from '../modes/trueFalse.js';
import type { AtomicFact, Category, CountryRecord } from './types.js';

/** Any unchanged pure rules-module pack generated by the product catalog. */
export type ProductPack = McPack | TfPack | TaPack | HlPack;

function visual(fact: AtomicFact): PresentedVisual | undefined {
  return fact.visual ? { ...fact.visual } : undefined;
}

/** Three stable, semantically compatible distractors from the same atomic pack. */
function distractors(category: Category, fact: AtomicFact, index: number): [string, string, string] {
  const pool = [...new Set(category.facts
    .filter((candidate) => candidate.packId === fact.packId)
    .map((candidate) => candidate.canonicalAnswer)
    .filter((answer) => answer !== fact.canonicalAnswer))];
  const wrong: string[] = [];
  for (let step = 0; step < pool.length && wrong.length < 3; step += 1) {
    const answer = pool[(index * 7 + step) % pool.length];
    if (answer && !wrong.includes(answer)) wrong.push(answer);
  }
  if (wrong.length !== 3) throw new Error(`${fact.id}: fewer than three unique distractors`);
  return wrong as [string, string, string];
}

function multipleChoice(category: Category): McPack {
  return {
    packId: `${category.packId}-mc`,
    questions: category.facts.map((fact, index) => ({
      prompt: fact.prompt,
      correct: fact.canonicalAnswer,
      wrong: distractors(category, fact, index),
      explanation: fact.explanation,
      ...(visual(fact) ? { visual: visual(fact) } : {}),
    })),
  };
}

function trueFalse(category: Category): TfPack {
  return {
    packId: `${category.packId}-tf`,
    labels: ['True', 'False'],
    questions: category.facts.flatMap((fact, index) => {
      const wrong = distractors(category, fact, index)[0];
      return [
        {
          statement: fact.statementTemplate.replace('{answer}', fact.canonicalAnswer),
          isTrue: true,
          explanation: fact.explanation,
          ...(visual(fact) ? { visual: visual(fact) } : {}),
        },
        {
          statement: fact.statementTemplate.replace('{answer}', wrong),
          isTrue: false,
          explanation: fact.explanation,
          ...(visual(fact) ? { visual: visual(fact) } : {}),
        },
      ];
    }),
  };
}

function typeAnswer(category: Category): TaPack {
  return {
    packId: `${category.packId}-type`,
    questions: category.facts.map((fact) => ({
      prompt: fact.prompt,
      acceptedAnswers: [fact.canonicalAnswer, ...fact.acceptedVariants],
      explanation: fact.explanation,
      ...(visual(fact) ? { visual: visual(fact) } : {}),
    })),
  };
}

function pairs(countries: readonly CountryRecord[]): HlPackQuestion[] {
  const result: HlPackQuestion[] = [];
  for (let firstIndex = 0; firstIndex < countries.length; firstIndex += 1) {
    for (let secondIndex = firstIndex + 1; secondIndex < countries.length; secondIndex += 1) {
      const first = countries[firstIndex]!;
      const second = countries[secondIndex]!;
      result.push({
        a: { label: first.name, value: first.area },
        b: { label: second.name, value: second.area },
      });
    }
  }
  return result;
}

function higherLower(category: Category): HlPack {
  return {
    packId: `${category.packId}-area-hl`,
    prompt: 'Which country has the larger total area?',
    unit: 'km²',
    explanation: 'Compared by total area, including inland water, using the frozen Factbook launch values.',
    questions: pairs(category.countries),
  };
}

/** Build the selected topic pack without pushing product state into a rules module. */
export function getPack(category: Category, modeId: ModeId): ProductPack {
  if (modeId === 'multiple-choice') return multipleChoice(category);
  if (modeId === 'true-false') return trueFalse(category);
  if (modeId === 'type-answer') return typeAnswer(category);
  return higherLower(category);
}
